Lubycon/lubycon-frontend-libraries

packages/react/src/hooks/useUpload.ts
packages/react/src/index.ts

파일 업로드 컴포넌틑 구현시 file, upload, reset,loading  구현을 쉽게 편의성있게 해주는 훅입니다.
```tsx
const {file,upload, loading,reset} = useUpload()
const on썸네일업로드 = async () => {
const file = await upload()
if (!file) return
}
return (
<>
<button onClick={on썸네일업로드}>썸네일업로드</button>
{file && <input readOnly value={file.name} />}
</>
)
```

feat: 파일업로드 useUpload hooks

---

.github/workflows/slack-notification.yml

chore: add mattermost config [skip ci]

---

packages/react/src/hooks/useAnimationFrame.ts

`requestAnimationFrame`을 추상화한 `useAnimationFrame` 훅을 추가합니다. 콜백의 레퍼런스가 변경되면 기존의 animationFrame을 취소하고 새로운 animationFrame을 등록하니, 최적화를 위해 콜백의 레퍼런스 관리를 신경써주세요.
```ts
const [progress, setProgress] = useState(0);
const updateProgress = useCallback(() => {
setProgress(prevProgress => prevProgress >= 100 ? 0 : prevProgress + 1);
}, []);
useAnimationFrame(updateProgress);
```
🙇

feat(react): useAnimationFrame 훅 추가

---

packages/utils/src/index.ts
packages/utils/src/localStorage/index.ts

`utils/localStorage.ts`에서만 `export` 되고 `utils/index.ts`에서 `export` 해주지 않아 추가했습니다

refactor(utils): add export LocalStorageChageEvent

---

packages/utils/src/index.ts
packages/utils/src/localStorage/index.ts
packages/utils/src/localStorage/localStorageEvent.ts

클래스가 트랜스파일 되면서 에러가 나고 있어 함수로 변경했슴당
- see also https://mattermost.lubycon.io/lubycon/pl/xhwwihtc93n5zc5azzqbpistwy

refactor(utils): change class to function

---

packages/utils/src/index.ts

refactor(utils): export type

---

.pnp.cjs
packages/utils/package.json
packages/utils/src/version/index.ts
yarn.lock

Semantic Version과 관련된 유틸들을 추가하였습니다.
시맨틱 버전을 major, minor, patch 키를 가진 객체로 파싱합니다.
```ts
parseSemanticVersion('1.2.3'); // { major: 1, minor: 2, patch: 3 }
```
인자로 주어진 major, minor, patch 버전을 'major.minor.patch'의 시맨틱 버전 형태의 문자열로 변환합니다.
```ts
stringifySemanticVersion({ major: 1, minor: 2, patch: 3 }); // 1.2.3
```
versionA와 versionB를 비교하여, versionA가 더 높다면 1, 같다면 0, 더 낮다면 -1을 반환합니다.
```ts
compareVersion('1.1.1', '1.0.0'); // 1
compareVersion('1.1.1', '1.1.1'); // 0
compareVersion('1.1.1', '1.2.1'); // -1
```
인자로 주어진 `versionA`가 `versionB`보다 더 높은 버전인지 확인합니다.
```ts
isGreaterSemanticVersion('1.12.1', '1.0.1'); // true
isGreaterSemanticVersion('1.12.1', '1.12.2'); // false
```
인자로 주어진 `versionA`가 `versionB`보다 더 낮은 버전인지 확인합니다.
```ts
isLessSemanticVersion('1.0.1', '1.1.1'); // true …
```

feat(utils): Semantic Version 관련 유틸들 추가

---

packages/react/src/hooks/useDidMount.ts
packages/react/src/hooks/useDidUpdate.ts
packages/react/src/hooks/useWillUnmount.ts
packages/react/src/index.ts

`DidMount`, `DidUpdate`, `WillUnmount` 라이프사이클 훅스 추가했습니다

feat(react): life cycle 추가

---

packages/react/src/hooks/useImpression.ts
packages/react/src/index.ts

제곧내입니다....ㅎㅎㅎ 기껏 만들어놓고 export를 안 하고 있었네유.... 🙏 
🙇

fix(react): export 되지 않고 있던 useImpression 훅 export

---

packages/utils/src/deviceDetector/global.d.ts
packages/utils/src/deviceDetector/index.ts
packages/utils/src/deviceDetector/presets.ts
packages/utils/src/deviceDetector/types.ts
packages/utils/src/deviceDetector/userAgent.ts
packages/utils/src/deviceDetector/userAgentData.ts
packages/utils/src/deviceDetector/utils.ts

device detector로 browser에 대한 정보, mobile, desktop, client, server와 같은 실행 환경에 대한 정보를 제공하는 유틸을 추가했습니다.
실행 환경이 mobile 환경인지 체크해 boolean값을 리턴합니다.
```
isMobile // true | false
```
실행 환경이 desktop 환경인지 체크해 boolean값을 리턴합니다.
```
isDesktop // true | false
```
실행 환경이 client인지 체크해 boolean값을 리턴합니다.
```
isClient // true | false
```
실행 환경이 server인지 체크해 boolean 값을 리턴합니다.
```
isServer // true | false
```
실행 환경에 browser 정보를 리턴합니다.
```
browser; // {name: browserName, version: browserVersion}
```
라이브러리를 처음 만들어봐서 많이 부족합니다! 🙏

feat(utils): device detector 추가

---

packages/react/src/index.ts

feat(react): useCombinedRefs, useScrollEvent 내보내기~

---

_templates/packages/new/package.json.ejs.t
_templates/packages/new/rollup.config.js.ejs.t
packages/logger/package.json
packages/mattermost/package.json
packages/react/package.json
packages/utils/package.json

이전 PR에서 누락된 부분을 추가합니다.
- `_templates` 내부에도 CJS, ESM 모듈링 설정 반영
- `lint` 스크립트가 없는 라이브러리에 `lint` 스크립트 추가
- `modules` 설정 반영이 안 되어 있는 라이브러리에 `modules` 설정 추가
🙇

fix(logger,mattermost,react,utils): 누락된 부분 추가

---

packages/mattermost/src/utils/http/handlers.ts

서버 환경에서는 전역에 선언된 `Header` 클래스가 없어서 에러가 발생하고 있읍니다.
:bow:

fix(mattermost): Header 클래스를 cross-fetch로부터 가져오도록 수정

---

.npmignore
packages/mattermost/src/client/index.ts
packages/mattermost/src/utils/http/handlers.ts
packages/mattermost/test/index.js

Mattermost API의 응답으로 올바른 JSON이 오지 않을 경우 응답 바디를 무시합니다.
:bow:

fix(mattermost): Incoming Webhook 응답으로 딸랑 "ok" 하나만 오는 경우 대응

---

packages/utils/src/promise/index.ts

- `defer` 함수의 설명을 추가합니다
- `sleep` 함수를 추가합니다
```ts
console.log('슬립 시작');
await sleep(1000);
console.log('1초 지남');
```
🙇

feat(utils): Sleep 함수 추가

---

CNAME.live
script/deploy.js

어떤 사항이 변경되었는지 자세히 적어주세요!
- fe-lib.lubycon.io  CNAME Generate

chore: typedoc publish CNAME file 추가 [skip ci]

---

packages/react/src/index.ts

제곧내입니다...!!! 루비콘 홈 작업할 때 쓰려고 했는데 없어서 당황쓰....
🙇

fix(react): useResizeObserver Export 안 되고 있던 이슈 수정

---

packages/utils/src/fetch/handlers.ts
packages/utils/src/fetch/utils.ts

제곧내입니다. 요 부분 때문에 빌드가 깨지고 있어유.
🙇

fix(utils): @lubycon/utils 모듈이 스스로를 참조하고 있는 부분 제거

---

packages/utils/src/uuid/index.ts

간단하게 UUID를 생성하는 함수를 만들었습니다!
- uuid 관련 유틸 함수 추가
잘 부탁드립니다. 감사합니다!. 🙏

feat(utils): uuid 생성 함수 추가

---

_templates/packages/new/package.json.ejs.t
_templates/packages/new/prompt.js

제곧내입니다. 이제 `@lubycon` 프리픽스 없애버리고, 이 플레이그라운드에서 만들고 싶은거 아무거나 자유롭게 만들어보시져 ㅋㅋㅋㅋ
🙇

chore: hygen 템플릿 생성 시 @lubycon 프리픽스 안 붙히도록 수정 [skip ci]

---

packages/temen/src/is/index.ts
packages/temen/test/is.test.js

lodash의 [isNil](https://lodash.com/docs/4.17.15#isNil) 추가합니다.
isNil 은 value가 null, undefined 인지 확인해줍니다.
```ts
isNil(null)  => true
isNil(void 0) => true
isNil(NaN) => false
```
기존에 있던 is directory 에 넣어놨는데 
1. 분리 하는게 나을까요 (isNil directory 생성)
2. is(check) 함수는 해당 directory 에 두는게 나을까요??

feat(temen): isNil 추가

---

packages/temen/src/index.ts

export되어있지 않던 model utils를 export 해줬습니다!

feat(temen): export되어있지 않은 utils 추가

---

packages/temen/test/cookies.test.js

[github workflows ]
- [gitActions] new Date() 시 =>Sat, 12 Feb 2022 00:00:00 GMT
- [local환경] new Date() => Fri, 11 Feb 2022 15:00:00 GMT
시간 차이가 나서 환경을 test 통일 시켰습니다.

fix(temen): cookies test code 수정

---

packages/temen/src/castArray/index.ts
packages/temen/src/index.ts
packages/temen/test/castArray.test.js

https://lodash.com/docs/4.17.15#castArray
**castArray** 추가 했슴당
🙇🏻‍♂️

feat(teman): castArray 추가

---

packages/temen/src/clone/index.ts
packages/temen/src/index.ts

https://lodash.com/docs/4.17.15#clone
**clone** 추가 했습니당
_**isObejct**는 lodash 에 있는 유틸인데 시간이 늦어서 isObject 는 만들지 못하고 여기서 마감...ㅠ_
잘부탁드립니다ㅏㅏㅏ

feat(temen): clone 추가

---

packages/temen/src/cloneDeep/index.ts
packages/temen/src/index.ts
packages/temen/test/cloneDeep.test.js

https://lodash.com/docs/4.17.15#cloneDeep 
**cloneDeep** 추가 했습니당

feat(temen): cloneDeep 추가

---

packages/temen/src/compact/index.ts
packages/temen/src/index.ts
packages/temen/test/compact.test.js

배열 내에서 Falsy 값을 제거하는 `compact` 함수를 추가합니다. 기존 lodash에서는 `for`문을 사용하고 있었는데, 동일한 동작을 `Array.prototype.filter`로 해결할 수 있어서 변경하였읍니다!
🙇

feat(temen): compact 함수 추가

---

packages/temen/src/index.ts
packages/temen/src/pick/index.ts
packages/temen/test/pick.test.js

lodash - [pick](https://lodash.com/docs/4.17.15#pick) 구현
pick 함수 추가 했습니다.!!!!

feat(temen): pick 함수 추가

---

packages/temen/src/pick/index.ts

`pick` 함수의 테스트가 깨지고 있는 부분을 수정합니다.
https://github.com/Lubycon/lubycon-frontend-libraries/runs/4187649150?check_suite_focus=true#step:8:38
🙇

fix(temen): pick 함수 테스트 깨지는 부분 수정

---

.github/CODEOWNERS
.github/workflows/pr-notification.yml

chore: PR봇 업데이트

---

packages/temen/src/cloneDeepWith/index.ts
packages/temen/src/index.ts
packages/temen/test/cloneDeepWith.test.js

lodash `cloneDeepWith` 추가 [참고](https://lodash.com/docs/4.17.15#cloneDeepWith)
customizer를 받으면 customizer 의 결과 값을 리턴합니다.
customizer를 받지 않으면 cloneDeep 동작과 동일합니다.
```js
function customizer(value) {
if (isElement(value)) {
return value.cloneNode(true);
}
}
const el = cloneDeepWith(document.body, customizer);
console.log(el === document.body);
// => false
console.log(el.nodeName);
// => 'BODY'
console.log(el.childNodes.length);
// => 20
```
많관부

feat(temen): cloneDeepWith 추가

---

.github/CODEOWNERS
.github/workflows/pr-notification.yml
packages/temen/src/_internal/getLongestArrayLength.ts
packages/temen/src/index.ts
packages/temen/src/unzip/index.ts
packages/temen/src/zip/index.ts
packages/temen/test/unzip.test.js

- [ x ] 내가 만든 모듈을 `export` 했나요?
- [ x ] 테스트는 작성했나요?
- [ x ] 내가 만든 모듈에 대한 설명이 `jsDoc` 포맷으로 잘 입력되어있나요?
- `zip`된 배열을 다시 해체하는 `unzip` 함수를 추가합니다.
- `zip` 함수에서 사용하던 "가장 긴 배열의 길이를 찾는 로직"을 `_internal/getLongestArrayLength`로 추상화합니다.
```ts
unzip(['a', 1, true], ['b', 2, false]]);
// [['a', 'b'], [1, 2], [true, false]]
unzip([['a', 1, true, 2], ['b', 2, false]]);
// [['a', 'b'], [1, 2], [true, false], [2, undefined]]
```
[lodash 스펙](https://lodash.com/docs/4.17.15#unzip)
🙇

feat(temen): unzip 함수 추가

---

packages/browser-toolkit/.vscode/settings.json
packages/browser-toolkit/README.md
packages/browser-toolkit/babel.config.json
packages/browser-toolkit/jest.config.json
packages/browser-toolkit/package.json
packages/browser-toolkit/rollup.config.js
packages/browser-toolkit/src/cookies/getOptionValue.ts
packages/browser-toolkit/src/cookies/index.ts
packages/browser-toolkit/src/cookies/parseCookies.ts
packages/browser-toolkit/src/cookies/stringifyCookie.ts
packages/browser-toolkit/src/copyToClipboard/index.ts
packages/browser-toolkit/src/deviceDetector/global.d.ts
packages/browser-toolkit/src/deviceDetector/index.ts
packages/browser-toolkit/src/deviceDetector/presets.ts
packages/browser-toolkit/src/deviceDetector/types.ts
packages/browser-toolkit/src/deviceDetector/userAgent.ts
packages/browser-toolkit/src/deviceDetector/userAgentData.ts
packages/browser-toolkit/src/deviceDetector/utils.ts
packages/browser-toolkit/src/fetch/handlers.ts
packages/browser-toolkit/src/fetch/index.ts
packages/browser-toolkit/src/fetch/utils.ts
packages/browser-toolkit/src/index.ts
packages/browser-toolkit/src/localStorage/index.ts
packages/browser-toolkit/src/localStorage/localStorageEvent.ts
packages/browser-toolkit/src/localStorage/storage.ts
packages/browser-toolkit/test/cookies.test.js
packages/browser-toolkit/tsconfig.json
packages/temen/src/localStorage/index.ts
tsconfig.doc.json

`temen` 내에 존재하는 브라우저API와 디펜던시가 있는 것들을 분리하여 `browser-toolkit` 라이브러리를 생성합니다.
분리되어야하지만 분리되지 않은 것/분리가 불필요하나 분리가 된 것 이 있는지 체크 부탁드립니다

chore: browser-toolkit 라이브러리 추가

---

packages/temen/src/index.ts
packages/temen/src/intersection/index.ts
packages/temen/test/diffference.test.js
packages/temen/test/intersection.test.js

인자로 받은 배열들을 비교하여 겹치는 원소만을 반환하는 `intersection`, `intersectionWith` 함수를 추가합니다.
```ts
intersectionWith([1, 2, 3], [2, 3, 4], (x, y) => x === y); // [2, 3]
intersectionWith(
[{ info: { id: 1 }, name: 'evan' }, { info: { id: 2 }, name: 'john' }],
[{ info: { id: 2 }, name: 'john' }],
(x, y) => x.info.id === y.info.id
); // [{ info: { id: 2 }, name: 'john' }]
```
```ts
intersection([1, 2, 3], [2, 3]); // [2, 3]
intersection(
[{ info: { id: 1 }, name: 'evan' }, { info: { id: 2 }, name: 'john' }],
[{ info: { id: 2 }, name: 'john' }],
); // [{ info: { id: 2 }, name: 'john' }]
```
저번에 만들었던 `difference`와 반대되는 동작을 하는 녀석이라 퀵하게 만들었읍니다. 그래서 테스트 케이스도 `difference.test.js`에서 복붙한다음에 약간 수정만 한 건데, 이 과정에서 혹시 빠진 부분은 없는지 같이 봐주시면 좋을 것 같아요 🙏

feat(temen): intersection, intersectionWith 추가

---

packages/browser-toolkit/src/fetch/index.ts

fix(browser-toolkit): fetcher 타입이 Promise<unknown>으로 잡히는 이슈 수정

---

packages/temen/src/drop/index.ts
packages/temen/src/index.ts
packages/temen/test/drop.test.js

배열의 원소를 제거하는 drop, dropRight 함수를 추가합니다.
```ts
drop([1, 2, 3], 1); // [2, 3]
dropRight([1, 2, 3], 1); // [1, 2]
```
🙇

feat(temen): drop, dropRight 함수 추가

---

packages/temen/src/_internal/getType.ts
packages/temen/src/index.ts
packages/temen/src/isArguments/index.ts
packages/temen/src/isArrayBuffer/index.ts
packages/temen/src/isArrayLike/index.ts
packages/temen/src/isArrayLikeObject/index.ts
packages/temen/src/isObjectLike/index.ts
packages/temen/test/is.test.js

is 함수들과의 끝을 보고자 했는데 처참히 패했습니다.
간단한 함수들이라 문서 첨부해두겠습니다!
- [isArguments](https://lodash.com/docs/4.17.15#isArguments)
- [isArrayBuffer](https://lodash.com/docs/4.17.15#isArrayBuffer)
- [isArrayLike](https://lodash.com/docs/4.17.15#isArrayLike)
- [isLArrayLikeObject](https://lodash.com/docs/4.17.15#isArrayLikeObject)
- [isObjectLike](https://lodash.com/docs/4.17.15#isObjectLike)
빼먹은 조건이 있을까요우..?
테스트코드는 어디까지 테스트 해야하는것인가...?

feat(temen): is functions 추가

---

packages/temen/src/debounce/index.ts
packages/temen/src/index.ts
packages/temen/test/debounce.test.js

어떤 사항이 변경되었는지 자세히 적어주세요!
debounce 함수를 추가 했습니다!
```ts
const callbackFunc = () => {
return 'callback'
}
const debounce(callback, 300);
```
잘 부탁드립니다. 🙏

feat(temen): debounce 함수 추가

---

packages/temen/src/groupBy/index.ts
packages/temen/src/index.ts
packages/temen/test/groupBy.test.js

배열의 원소를 특정한 규칙으로 그룹핑할 수 있는 `groupBy` 함수를 추가합니다.
```ts
groupBy([6.1, 4.2, 6.3], Math.floor);
// { 4: [4.2], 6: [6.1, 6.3] }
groupBy(
[
{ age: 31, name: 'evan' },
{ age: 32, name: 'john' },
{ age: 25, name: 'kevin' },
],
({ age }) => `${Math.floor(age / 10) * 10}대`
)
// { '20대': [{ age: 25, name: 'kevin' }], '30대': [{ age: 31, name: 'evan' }, { age: 32, name: 'john' }]}
```
얼마 전에 회사에서 어드민 작업하다가 이 함수 썼는데 넘나 편했던 기억이 나서, 생각난 김에 추가합니당

feat(temen): groupBy 함수 추가

---

packages/logger/src/loggers/amplitude/index.ts

- [🙏] 내가 만든 모듈을 `export` 했나요?
- [🙏] 테스트는 작성했나요?
- [🙏] 내가 만든 모듈에 대한 설명이 `jsDoc` 포맷으로 잘 입력되어있나요?
어떤 사항이 변경되었는지 자세히 적어주세요!
Logger에서 사용하는 Amplitude에 Props를 변경했습니다.
`as`
```
export const initializeAmplitude = (apiKey: string) => {
...blabla
}
```
`to be`
기존에 `apiKey` 만 받고있던 props에 `userId`와 `options` 를 추가했습니다.
```
interface AmplitudeConfig {
apiKey: string;
userId?: string;
options?: Config; // amplitude Config Type
}
export const initializeAmplitude = (config: AmplitudeConfig) => {
const { apiKey, userId="unknown", options: {} } = config;
amplitudeModule.default
.getInstance()
.init(apiKey, userId, options, async (client: AmplitudeClient) => {
}
```
- amplitude config props 변경
잘 부탁드립니다 🙏

feat(logger): amplitude config 변경

---

README.md
packages/browser-toolkit/src/querystring/index.ts
packages/temen/src/clone/index.ts
packages/temen/src/cloneDeep/index.ts
packages/temen/src/cloneWith/index.ts
packages/temen/src/date/index.ts
packages/temen/src/isError/index.ts
packages/temen/src/promise/index.ts
packages/temen/src/queryString/index.ts

마크다운 양식으로 작성 되지 않았던 예제코드에 마크다운을 추가 했습니다.
README 에 문서 및 체인지로그 첨부했습니다.

docs: 예제 코드 마크다운 추가 [skip ci]

---

.vscode/settings.json
packages/temen/src/index.ts
packages/temen/src/isNull/index.ts
packages/temen/src/isObject/index.ts
packages/temen/src/isPlainObject/index.ts
packages/temen/src/isSafeInteger/index.ts
packages/temen/test/is.test.js

- isNull, isPlainObject, isObject 함수 추가 했습니다.
prettier 동작이 제대로 하지 않아 settings json 설정도 제거했는데 제거해도 문제 없을까요?

feat(temen): isNull, isPlainObject, isObject

---

packages/temen/src/castArray/index.ts
packages/temen/src/cloneDeepWith/index.ts
packages/temen/src/cloneWith/index.ts
packages/temen/src/gt/index.ts
packages/temen/src/gte/index.ts
packages/temen/src/isArguments/index.ts
packages/temen/src/isArrayBuffer/index.ts
packages/temen/src/isArrayLike/index.ts
packages/temen/src/isArrayLikeObject/index.ts
packages/temen/src/isBuffer/index.ts
packages/temen/src/isNull/index.ts
packages/temen/src/isObject/index.ts
packages/temen/src/isPlainObject/index.ts
packages/temen/src/isSafeInteger/index.ts

타입스크립트 기반으로 작성에 맞게 jsdoc의 파라미터 값을 와일드카드(*)에서 `any` 로 변경했습니다.

docs(teman): jsdoc 와일드카드(*) any 로 변경

---

packages/temen/src/index.ts
packages/temen/src/isNative/index.ts
packages/temen/src/isSymbol/index.ts
packages/temen/src/isWeakMap/index.ts
packages/temen/src/isWeakSet/index.ts
packages/temen/test/is.test.js

isNative, isWeakMap, isWeakSet 유틸 추가 했습니다.
is... 함수들 드디어 끝났습니다 🔥

feat(teman): is 함수들 추가

---

packages/icons/src/components/Icon/index.tsx

제곧내입니다! 디펜던시 어레이에 `iconName`이 빠져있었읍니다....이거 eslint 룰 달아둬야겠네여
:bow:

fix(icons): 아이콘 이름이 바뀌어도 컴포넌트가 리렌더링되지 않는 이슈 수정

---

packages/temen/src/cloneDeep/index.ts
packages/temen/test/cloneDeep.test.js

- RegExp 객체를 복사할 수 있도록 변경했습니다.
- 중복 기능 제거 하였습니다.
🙇🏻

feat(temam): cloneDeep 함수 고도화

---

packages/temen/src/index.ts
packages/temen/src/lt/index.ts
packages/temen/src/toArray/index.ts
packages/temen/test/lt.test.js
packages/temen/test/toArray.test.js

- toArray 함수 추가
- lt, lte(less than[equal]) 함수 추가
슥슥 추가했습니다

feat: lt, toArray 추가

---

.github/workflows/tests.yml
.husky/post-merge
.husky/pre-commit
package.json

- 새로운 패키지를 생성하거나 리모트 저장소의 변경사항을 머지한 경우 `yarn && yarn build:all`이 실행되어 패키지 참조 정합성을 유지합니다.
- PR 생성 시 `lint`, `test`, `typecheck` 3가지 작업이 수행되도록 변경합니다.

chore: 패키지 정합성을 위한 작업들 추가

---

packages/react/src/hooks/useDetectEscapeKey.ts
packages/react/src/index.ts

esc 키를 감지하여 상태를 반환하는 훅입니다.
```ts
const isEscapeKeyPressed = useDetectEscapeKey();
useEffect(()=>{
if(isEscapeKeyPressed) console.log("pressed esc");
},[isEscapeKeyPressed])
```
🔥

feat(react): useDetectEscapeKey 추가

---

packages/react/src/_internal/Key.ts
packages/react/src/hooks/useDetectEscapeKey.ts
packages/react/src/hooks/useDetectKeyPress.ts
packages/react/src/index.ts

매게변수로 전달 받은 키를 감지하는 `useDetectKeyPress` 추가 했습니다.
```ts
const pressedKey = useDetectKeyPress('Escape', callback);
console.log(pressedKey); // Escape 키가 눌렸을 때 Escape 출력
```

feat(react): useDetectKeyPress 추가

---

packages/react/src/index.ts

fix(react): useOverlay export 빼먹은 거 수정

---

packages/react/src/hooks/useResizeObserver.ts

다른 작업하다가 우연히 발견한 타입 찐빠를 수정합니다. 쓸데없이 복잡하게 작성된 부분도 있어서 `useImpression`이랑 동일한 로직으로 Observer를 사용하도록 수정합니다.

fix: useResizeObserver 타입 찐빠 수정

---

packages/temen/src/index.ts

fix(temen): 빼먹은 export 추가
