Lubycon/lubycon-frontend-libraries

- .pnp.cjs
- packages/react/package.json
- packages/react/src/hooks/useQueryParam.ts
- yarn.lock
- `useQueryParam` 훅을 추가합니다.
- `@lubycon/react` 패키지에 `@lubycon/utils` 디펜던시를 걸었읍니다
```ts
import { useQueryParam } from '@lubycon/react';
const foo = useQueryParam('foo', Number) ?? -1; // number | undefined
const bar = useQueryParam('bar'); // string | undefined
const baz = useQueryParam('baz') ?? 'empty'; // string
```
🙇
> feat(react): useQueryParam 훅 추가

- packages/logger/package.json
- packages/mattermost/package.json
- packages/react/package.json
- packages/utils/package.json
`next.js`에서 esm방식의 exports를 읽어오지 못해, 다시 commonjs방식으로 변경하였습니다.
commonjs방식으로 변경하였기 때문에, Tree shaking이 지원되지 않습니다😂
esm방식 exports를 적용하는 자에게 동욱님@evan-moon 이 포상해주신다고 합니다🎉
🙏
> chore: 패키지 exports를 다시 commonjs로 변경

- packages/react/src/hooks/useImpression.ts
엘리먼트의 노출 여부를 알 수 있는 `useImpression` 훅을 추가합니다.
요 녀석으로 `@lubycon/ui-kit`의 `Icon` 컴포넌트가 실제 화면에 보여질 때만 `assets.lubycon.io`로 아이콘을 요청하도록 만들 예정입니다!
```tsx
const ref = useImpression({
onImpressionStart: () => { console.log('보인다!') },
onImpressionEnd: () => { console.log('숨었다!') },
});
return <div ref={ref} />
```
🙇
> feat(react): useImpression 훅 추가

- packages/react/src/hooks/useCombinedRef.ts
- packages/react/src/hooks/useScrollEvent.ts
`@lubycon/ui-kit`에서 사용하던 `useCombinedRefs`, `useScroll` 훅을 `@lubycon/react`에 옮겼습니다.
여러 개의 ref를 합칠 수 있는 훅입니다.
```tsx
const Foo = forwardRef((props, fowardedRef) => {
const ref = useRef();
const combinedRef = useCombinedRefs(fowardedRef, ref2);
// div가 업데이트되면 ref, fowardedRef 둘 다 업데이트 됨
return <div ref={combinedRef} />
});
```
```tsx
const Foo = () => {
const ref = useRef();
const callback = useCallback(() => {
console.log('scroll 이벤트 발생');
});
useScrollEvent(ref, callback);
return <div ref={ref} />;
};
```
🙇
> feat(react): useCombinedRefs, useScrollEvent 훅 추가

- packages/react/src/hooks/useClipboardCopy.ts
- packages/react/src/hooks/useDidUpdate.ts
- 매개변수로 주어진 string을 clipboard copy 하는 함수를 반환하는 hook을 추가하였습니다. 
- example
```javascript
const Foo = () => {
const { copyString } = useClipboardCopy();
return (
<button onClick={() => copyString('https://lubycon.io/')}>공유하기<button/>
);
};
```
> feat(react):  useClipboardCopy hook 추가

- .vscode/settings.json
- vscode에서 탭사이즈 2 + 탭 대신 스페이스 사용하도록 명시
- 디폴트 포매터 prettier-eslint로 사용하도록 추가
- vscode 밑에 tab 4 뜨는게 영 찜찜하기도 하고, format on save 하기 전에 명시적으로 잡아주는게 더 좋을 것 같아서 둘 다 추가해주었습니다
- 제 vscode 글로벌 설정이랑 루비콘 설정이랑 안맞는 부분이 있어서 추가하였습니다 🙏
> [skip ci] chore: vscode config

- packages/react/src/hooks/useLocalStorage.ts
- packages/react/src/hooks/useQueryParam.ts
- useLocalStorage의 기본 상태할당 로직 변경
- 해당 상태할당에서 window 환경에 접근하기 때문에 서버사이드 환경에서 오류가 발생해서, utils의 getLocalStorageItem을 통해 기본 상태 할당해주도록 변경하였습니다
- useEffect 부분에서 state가 null인 경우 다시 set하는 로직이 있어서 이 시점에서 로컬스토리지에 의도하는 정보가 설정됩니다
- 동욱님이 전에 얘기주셨던 로컬스토리지랑 훅의 스테이트랑 같이 변해야 하는것 아니냐고 하신 부분은 로직중에 `onLocalStorageChange` 이벤 트에서 처리하고 있습니다 -!
- useQueryParam 리턴 로직을 useMemo에서 useState + useEffect로 변경하였습니다
- 값이 없는 경우 undefined 리턴을 의도하시는 것 같아서 그대로 사용했습니다 -
- 기존에 null인 경우 undefined를 리턴하도록 되어 있었는데, `query[key]`의 리턴 예상 값이 `string | undefined` 여서 undefined인 경우 그대로 undefined를 리턴하도록 변경했습니다
> fix(libraries): ssr issues

- .github/workflows/typedoc-publish.yml
- tsconfig.doc.json
typedoc-publish.yml 
docs:generate 실행시: @lubycon/패키지 참조를 못하는 error
[추가]
```
yarn install --immutable --immutable-cache
```
gitAction CI 돌렸을때 
@lubycon/패키지 참조를 못하는 error가 발생합니다. 🤔
yarn install --immutable --immutable-cache, yarn install 과 크게 차이가 있을까요?
> fix: typedoc publish action 수정 [skip ci]

- tsconfig.doc.json
- 임시 icons 패키지 컴포넌트는 typedoc generate 제외 시켰습니다.
> fix: icons 패키지 typedoc 제외 [skip ci]

- packages/utils/src/copyToClipboard/index.ts
- packages/utils/src/deviceDetector/utils.ts
- packages/utils/src/index.ts
- `@lubycon/utils`에 `copyToClipboard` 함수를 추가합니다.
내부적으로는 크로스 브라우징에 대한 예외처리를 진행하고 있지만, 함수의 출력 타입을 `Promise<boolean>`으로 통일해서, 구현을 캡슐화합니다.
```ts
const result = await copyToClipboard('하이');
if (result) {
console.log('클립보드에 복사 성공');
} else {
console.log('클립보드에 복사 실패');
}
```
`textarea.select()`를 사용하는  방법이 iOS에서 간혹 문제가 발생했던 것 같은데, 추후 이 부분에 대한 테스트가 필요할 것 같습니다.
> feat(utils): copyToClipboard 함수 추가

- packages/utils/src/date/index.ts
- cjs 환경에서는 node_modules에서 참조하는 date-fns 함수의 모듈 export 방식이 esm인 경우 실행이 안되므로 해당 부분 특정 모듈 지정해서 불러오도록 수정하였습니다
> fix(utils): date-fns module import way - esm to cjs

- packages/utils/src/array/createFromArray.ts
- packages/utils/src/array/getArrayFromCount.ts
- packages/utils/src/index.ts
인자로 받은 배열을 Map 구조로 변경하는 함수인 `createMapFromArray`와 `createObjectFromArray`를 추가합니다.
백엔드로 받아온 `T[]` 배열 내부의 아이템에 자주 접근해야 하는 상황이거나, 특정한 아이템을 캐싱해야하는 상황에서 유용하게 사용할 수 있습니다.
Map과 Object의 용법 자체는 크게 다르지 않지만, 키에 할당할 수 있는 타입이나 내부를 순회할 때 순서가 보장되는지 여부 등 세세한 부분에서 차이가 있으므로 두 가지 타입을 모두 제공합니다.
이 두 가지 타입의 차이에 대한 자세한 내용은 MDN의 [키기반의 컬렉션](https://developer.mozilla.org/ko/docs/Web/JavaScript/Guide/Keyed_collections) 문서를 참고해주세요.
인자로 받은 `T[]` 배열을 기반으로 `key`를 키 값으로 가지는 Map을 생성합니다.
```ts
interface Foo {
id: string;
name: string;
}
const fooList: Foo[] = [];
createMapFromArray(fooList, 'id'); // Map<string, Foo>
```
인자로 받은 `T[]` 배열을 기반으로 `key`를 키 값으로 가지는 Object를 생성합니다.
```ts
interface Foo {
id: string;
name: string;
}
const fooList: Foo[] = [];
createObjectFromArray(fooList, 'id'); // Record<string, Foo>
```
🙇
> feat(utils): createMapFromArray, createObjectFromArray 추가

- packages/utils/src/index.ts
- packages/utils/src/svg/index.ts
`@lubycon/utils`에 SVG 호를 편하게 그릴 수 있는 유틸을 추가합니다.
SVG의 호는 `circle` 처럼 따로 엘리먼트가 제공되는 것이 아니기 때문에 `path` 엘리먼트의 `A` 명령어를 사용해서 그려야 합니다.
하지만 호는 사람이 일반적으로 인식하는 "중심축 기준으로 n도 벌어진 모양"이라는 인터페이스를 가지고 있지 않고, 가상의 원을 먼저 정의하고 해당 원의 원주 위에서 시작점과 끝점을 정의하는 인터페이스를 가지고 있기 때문에, 처음 사용하는 사람에게는 다소 난해한 인터페이스입니다.
결국 호를 원하는 대로 그리기 위해서는 삼각함수를 사용해야 하는데, 이걸 매번 계산하기가 여간 귀찮은 일이 아니므로, 유틸을 추가합니다.
SVG의 호는 단순히 호를 그리는 것 뿐만 아니라 클립패스를 사용하여 도넛 차트의 애니메이션을 만드는 데에도 필수적으로 동반되기 때문에, 여러모로 활용도가 높습니다.
인자로 주어진 중심 좌표를 `x`, `y`로 가지고 반지름이 `radius` 만큼인 원을 기준으로 `degree` 만큼 벌어진 곳의 좌표를 구합니다.
```ts
getCoordsOnCircle({ x: 50, y: 50, radius: 50, degree: 90 }); // { x: 50, y: 100 }
```
중심 좌표 (x, y)를 기준으로 `degree(θ)`만큼 시계 방향으로 호를 그리는 SVG 패스 명령어를 반환합니다.
```tsx
const ArcSvg = () => {
return (
<svg width={100} height={100}>
<path d={getArc({ x: 50, y: 50, …
```
> feat(utils): SVG 호 관련 유틸들 추가

- packages/utils/jest.config.json
- packages/utils/src/cookies/getOptionValue.ts
- packages/utils/src/cookies/index.ts
- packages/utils/src/cookies/parseCookies.ts
- packages/utils/src/cookies/stringifyCookie.ts
- packages/utils/src/functions/index.ts
- packages/utils/src/index.ts
- packages/utils/test/cookies.test.js
- packages/utils/test/is.test.js
Cookie를 관리할 수 있는 유틸 함수를 추가합니다.
그리고 자매품으로 항등함수인 `identify` 함수도 하나 추가합니다. 이 함수의 용도는 주로 함수를 합성할 때 함수의 공역을 제한하고, 쓸데없는 사이드 이펙트의 발생을 방지하기 위해 사용합니다. 혹시 잘 이해가 안 가신다면 `getOptionValue` 같은 함수를 보시면 금방 아실 수 있을 것 같슴다. 🙏 
```ts
setCookie('foo', 1);
setCookie('bar', 1, { expires: new Date('2021-11-25') });
const cookies = getCookies(); // Record<string, string>
const foo2 = getCookie('foo') // string | undefined
const foo3 = getCookie('foo', Number) // number | undefined
```
:bow:
> feat(utils): cookie 유틸 추가

- packages/temen/src/difference/index.ts
- packages/temen/src/index.ts
- packages/temen/test/diffference.test.js
인자로 주어진 두 배열 간의 차이점을 반환하는 `differenceWith` 함수를 추가합니다.
`differenceWith + deepEqual` 함수가 `difference<T>(x: T[], y: T[])`  함수이기 때문에, `difference` 함수를 만들기 위한 재료이기도 합니다.
```ts
differenceWith([1, 2, 3], [2, 3], (x, y) => x === y); // [1]
differenceWith(
[{ info: { id: 1 }, name: 'evan' }, { info: { id: 2 }, name: 'john' }],
[{ info: { id: 2 }, name: 'john' }],
(x, y) => x.info.id === y.info.id
); // [{ info: { id: 1 }, name: 'evan' }]
```
:bow:
> feat(temen): differenceWith 함수 추가

- packages/temen/src/cloneWith/index.ts
- packages/temen/src/index.ts
- packages/temen/test/cloneWith.test.js
lodash `cloneWith` 추가 [참고](https://lodash.com/docs/4.17.15#cloneWith)
customizer를 받으면 customizer 의 결과 값을 리턴합니다.
customizer를 받지 않으면 clone 동작과 동일합니다.
```js
function customizer(value) {
if (isElement(value)) {
return value.cloneNode(false);
}
}
const el = cloneWith(document.body, customizer);
console.log(el === document.body);
// => false
console.log(el.nodeName);
// => 'BODY'
console.log(el.childNodes.length);
// => 0
```
많관부
> feat(temen): add cloneWith

- packages/temen/src/index.ts
- packages/temen/src/zip/index.ts
- packages/temen/test/zip.test.js
- [ x ] 내가 만든 모듈을 `export` 했나요?
- [ x ] 테스트는 작성했나요?
- [ x ] 내가 만든 모듈에 대한 설명이 `jsDoc` 포맷으로 잘 입력되어있나요?
인자로 받은 배열들 내에서 같은 인덱스에 있는 원소들을 그룹핑하는 `zip` 함수를 추가합니다.
lodash 스펙은 [여기](https://lodash.com/docs/4.17.15#zip)
```ts
zip(['a', 'b'], [1, 2]);
// [['a', 1], ['b', 2]]
zip(['a', 'b'], [1, 2, 3]);
// [['a', 1], ['b', 2], [undefined, 3]]
```
타입스크립트의 오버로딩의 한계로 인해 5개의 인자까지만 받을 수 있도록 타이핑되었습니다 ㅜㅜㅜㅜ....
lodash도 그렇고 예전에 RxJS도 그렇고 이런 식으로 구현하던데...더 좋은 방법이 없을까유 🧐
> feat(temen): zip 함수 추가

- .pnp.cjs
- packages/temen/src/index.ts
- packages/temen/src/uniq/index.ts
- packages/temen/test/isEqual.test.js
- packages/temen/test/uniq.test.js
- yarn.lock
배열 내의 중복되는 원소를 제거하는 `uniq`, `uniqBy` 함수를 추가합니다.
lodash는 직접 배열을 순회돌며 `include 되어있니?`를 계속 물어보는 식으로 작성되어있던데, 유일한 값이나 레퍼런스만을 받아들이는 [Set](https://developer.mozilla.org/ko/docs/Web/JavaScript/Reference/Global_Objects/Set)의 특성을 사용하면 굳이 이럴 필요없이 한 큐에 해결됩니다.
```ts
uniq([1, 1, 2, 3, 5, 5, 7, 'foo', 'bar', 'bar']); // [1, 2, 3, 5, 7, 'foo', 'bar']
const o = { id: 1 };
const array = uniq([o, o]); // [{ id: 1 }]
array[0] === o; // true, 원소의 레퍼런스는 변하지 않는다.
uniqBy([1.2, 1.5, 2.1, 3.2, 5.7, 5.3, 7.19], Math.floor); // [1, 2, 3, 5, 7]
```
:bow:
> feat(temen): uniq, uniqBy 함수 추가

- packages/temen/src/index.ts
- packages/temen/src/max/index.ts
- packages/temen/src/min/index.ts
- packages/temen/src/sum/index.ts
- packages/temen/test/max.test.js
- packages/temen/test/min.test.js
- packages/temen/test/sum.test.js
원소들의 값을 합산하는 `sum`, 최대 값을 찾는 `max`, 최소 값을 찾는 `min` 함수를 추가합니다.
`max`, `min` 같은 경우는 `Math.max`, `Math.min`이랑 다를게 없긴 한데, `maxBy`, `minBy` 같은 친구들이 은근 유용해여.
`maxBy`, `minBy` 함수가 뱉어주는 원소는 기존 배열에 있던 녀석을 그대로 반환하므로 레퍼런스가 변경되지 않습니다.
```ts
const users = [{ name: '문동욱', age: 31 }, { name: '홍길동', age: 25 }, { name: '김영란', age: 18 }];
const 평균_나이 = Math.floor(sumBy(users, ({ age }) => age) / users.length); // 24
const 제일_늙은_사람 = maxBy(users, ({ age }) => age); // { name: '문동욱', age: 31 }
const 제일_어린_사람 = minBy(users, ({ age }) => age); // { name: '김영란', age: 18 }
```
🙇
> feat(temen): sum, max, min 함수 추가

- packages/temen/src/average/index.ts
- packages/temen/src/index.ts
- packages/temen/test/average.test.js
데이터 집합의 평균을 계산하는 함수들을 추가합니다. 
주어진 데이터 집합의 합을 원소의 개수로 나누어 산술평균을 구합니다. lodash에는 [mean](https://lodash.com/docs/4.17.15#mean)으로 정의되어있는데 `average`가 좀 더 일반적인 단어인 것 같아서 변경했어유.
```ts
average([1, 2, 3]); // 2.5
averageBy([{ value: 1 }, { value: 2 }, { value: 3 }], ({ value }) => value); // 2.5
```
산술 평균의 최대 단점인 시간복잡도가 O(n)이라는 부분을 개선하여, 항상 O(1)의 시간복잡도를 보장하는 평균필터 알고리즘을 사용하는 함수입니다.
빠른 속도로 많은 양의 데이터가 입력되고, 그에 대한 후처리가 동반되어야하는 센서 이벤트 등의 상황에 적합합니다. 
```ts
let averageLux = 0;
let calcCount = 0;
const sensor = new AmbientLightSensor();
sensor.onreading = () => {
calcCount++;
averageLux = cumulativeAverage(averageLux, sensor.illuminance, calcCount);
console.log(`지금까지의 평균 조도는 ${averageLux}lux 입니다`);
};
sensor.start();
```
`cumulativeAverage` 함수는 사용자가 직접 "지금까지의 평균 값"과 "데이터 집합의 크기" 상태를 관리해줘야 하는 번거로움이 있기 때문에, …
> feat(temen): 평균 계산하는 함수들 추가

- packages/temen/src/models/utils.ts
예전에 만들어 둔 `Unwrap<T>` 타입 시리즈를 추가합니다. 간혹 `Promise<T>`, `Array<T>` 같은 제네릭 타입의 타입을 벗겨내야 하는 경우가 발생하는데, 요럴때 사용하는 녀석이에유.
```ts
type SingleDepthArray = UnwrapArray<string[]>; // string
type MultiDepthArray = UnwrapArray<string[][]>; // string
type UnionPromise = UnwrapArray<boolean | string[]>; // boolean | string
type SingleDepthPromise = UnwrapPromise<Promise<string>>; // string
type MultiDepthPromise = UnwrapPromise<Promise<Promise<string>>>; // string
type UnionPromise = UnwrapPromise<boolean | Promise<string>>; // boolean | string
```
사실 `UnwrapPromise<T>`는 최신 버전인 TypeScript 4.5에서 추가된 [Awaited](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-4-5.html#the-awaited-type-and-promise-improvements) 타입과 정확히 동일한 동작을 하는 녀석이기는 한데, 그 이하 버전에서는 요런 타입이 없었기 때문에 직접 만들어서 써야합니다.
🙇
> feat(temen): unwrap하는 타입 추가

- packages/browser-toolkit/src/fetch/index.ts
`browser-toolkit` 내부에서 `LubyconResponse` 타입을 `temen/dist/types/fetch/handlers`에서 가져오고 있는 버그를 수정합니다. 저번에 마이그레이션하다가 경로가 자동완성 되버린 듯...?
🙇
> fix(browser-toolkit): temen의 dist 디렉토리를 참조하고 있는 부분 제거

- packages/temen/src/flatten/index.ts
- packages/temen/src/index.ts
- packages/temen/test/flatten.test.js
고차원의 배열을 Flatten하는 `flatten`, `flattenDeep` 함수를 추가합니다.
---
물론 Native JS에도 `Array.prototype.flat` 메소드가 있기는 하지만, 아직 최적화가 되지 않았다고 하는 [Stack Overflow 글](https://stackoverflow.com/questions/61411776/is-js-native-array-flat-slow-for-depth-1)을 보았는데요.
그래서 조금 리서치를 해보니까 실제로 여러가지 방법으로 flatten을 구현하고 [벤치마킹을 했던 분](https://melkornemesis.medium.com/6-different-array-flattening-methods-in-javascript-performance-testing-included-cbadd928cf62)이 있더라구요.
근데 이 두 글 모두 2020년 4월, 8월 글이라, 조금 못 미더워서 저도 저 포스팅에서 진행했던 벤치마킹 테스트를 해봤는데...
```
// small: 10depth, medium: 15depth, big: 25depth
[native] small: 0.389ms
[native] medium: 8.419ms
[native] big: 7.504s
[reduce] small: 2.132ms
[reduce] medium: 22.629ms
[reduce] big: 13.096s
[recursion] small: 0.517ms
[recursion] medium: 6.391ms
[recursion] big: 983.285ms
```
NodeJS …
> feat(temen): flatten 함수 추가

- packages/temen/src/_internal/convertFirstLetter.ts
- packages/temen/src/_internal/convertSpecialCharacters.ts
- packages/temen/src/camelCase/index.ts
- packages/temen/src/convertFirstLetter/index.ts
- packages/temen/src/index.ts
- packages/temen/src/parscalCase/index.ts
- packages/temen/src/trimCharacters/index.ts
- packages/temen/test/camelCase.test.js
- packages/temen/test/convertFirstLetter.test.js
- packages/temen/test/parscalCase.test.js
- packages/temen/test/trimCharacters.test.js
`parscalCase`, `camelCase`, `upperFirstLetter`, `lowerFirstLetter`, `trimCharacters`, `trimStartCharacters`, `trimEndCharacters` 함수를 추가합니다.
인자로 받은 문자열을 각각 ParscalCase, camelCase로 변환합니다. 두 번째 인자인 splitter를 사용하면 특정한 문자를 기준으로 단어가 나누어졌다는 것을 표현할 수 있습니다. (왜인지 모르겠지만 `parscalCase`함수는 lodash에 없어서 추가했슴다)
```ts
parscalCase('camelCase'); // CamelCase
parscalCase('foo&bar-baz', ['&', '-']); // FooBarBaz
camelCase('ParscalCase'); // parscalCase
camelCase('foo&bar-baz', ['&', '-']); // fooBarBaz
```
인자로 받은 문자열의 가장 첫 번째 문자를 대,소문자로 변경합니다. 가장 첫 번째 문자가 영문이 아닌 경우 변경을 수행하지 않습니다.
```ts
lowerFirstLetter('FRED'); // fRED
lowerFirstLetter('1FRED'); // 1FRED
upperFirstLetter('fred'); // Fred
upperFirstLetter('1fred'); // 1fred
```
기본적으로는 공백을 찾아 trimming하지만, `targetCharacter` 인자에 값을 추가하면 해당 문자들을 찾아서 trimming합니다. …
> feat(temen): 문자열 포맷 함수 시리즈 추가

- packages/browser-toolkit/src/index.ts
- packages/browser-toolkit/src/loadScript/index.ts
비동기적으로 외부에서 스크립트를 불러오는 `loadScript` 함수를 추가합니다. 함수의 두 번째 인자로 `async`, `defer` 속성을 넘길 수 있습니다.
```ts
await loadScript('https://developers.kakao.com/sdk/js/kakao.js');
window.Kakao.init('my-token');
```
:bow:
> feat(browser-toolkit): loadScript 함수 추가

- packages/browser-toolkit/src/fetch/handlers.ts
- packages/browser-toolkit/src/fetch/index.ts
- packages/browser-toolkit/src/fetch/models.ts
- packages/browser-toolkit/src/fetch/utils.ts
현재 `LubyconResponse<T>` 인터페이스는 요청 성공, 에러 상태를 모두 포함하고 있기 때문에 `LubyconResponse<T>.data`의 nullish 여부를 통해서만 요청 실패 여부를 파악할 수 있습니다.
`responseHandler`에서 명시적으로 상태코드 200 이상 400미만 코드에 대해서만 성공처리를 하도록 변경하고, 나머지 상태코드는 직접 `LubyconErrorResponse` 객체를 throw 하도록 변경하여, fetch 함수 외부에서 `try/catch`로 에러 처리를 용이하게 할 수 있도록 변경합니다.
1. `react-query`의 `data`프로퍼티와 겹치지 않도록 `LubyconResponse` 타입이 응답 바디를 `data`가 아니라 `body` 프로퍼티를 사용하여 내보내도록 수정. (`data.data`처럼 접근하지 않기 위함)
2. `LubyconSuccessResponse`로 평가된 경우, `body` 가 `T | null`이 아닌 `T`임을 보장하여 요청이 성공했을때 `LubyconSuccessResponse.body`의 nullish 여부를 체크하지 않아도 되도록 수정.
3. `LubyconErrorResponse`로 평가된 경우, `body`가  반드시 `null`임을 보장하고 에러가 발생한 이유가 상태 코드 때문인지, 응답 바디를 파싱하다 발생한 것인지를 구분.
🙇
> feat(browser-toolkit): 통신에 실패했을 때 fetch 함수 내부에서 명시적으로 에러를 던지도록 수정

- packages/react/src/components/SSRSuspense.tsx
- packages/react/src/index.ts
아직 Next와 같은 SSR 환경에서 Suspense가 제대로 지원되고 있지 않기 때문에, Suspense를 사용하려면 SSR, CSR 환경에 따른 예외처리를 따로 해줘야 합니다.
그런 이유로 SSR 환경에서는 fallback을 렌더하는 `SSRSuspense` 컴포넌트와 `withSSRSuspense` HoC를 추가하여, 이 예외처리를 위임할 수 있도록 합니다.
```jsx
<SSRSuspense fallback={<Loading />}>
<MyPage />
</SSRSuspense>
// or
export default withSSRSuspense(<MyPage />, { fallback: <Loading /> });
```
:bow:
> feat(react): SSRSuspense 추가

- packages/temen/src/getArrayFromCount/index.ts
- packages/temen/test/getArrayFromCount.test.js
`getArrayFromCount` 함수의 반환 타입이 항상 `unknown[]`으로 잡히는 이슈를 제대로 된 오버로딩을 통해 수정합니다.
🙇
> fix(temen): getArrayFromCount의 반환 타입이 unknown[]으로 잡히는 이슈 수정

- packages/temen/src/index.ts
- packages/temen/src/omit/index.ts
- packages/temen/src/pick/index.ts
- packages/temen/test/omit.test.js
객체를 인자로 받고, 원하는 키를 제거한 새로운 객체를 반환하는 `omit` 함수를 추가합니다.
```ts
const foo = { a: 1, b: '2', c: true, d: 1 };
const omitted = omit(foo, ['a', 'c']); // { b: '2', d: 1 }
```
🙇
> feat(temen): omit 함수 추가

- packages/temen/src/mapKeys/index.ts
- packages/temen/src/mapValues/index.ts
- packages/temen/test/mapObject.test.js
`mapKeys`, `mapValues`의 jsDoc을 업데이트합니다.
- 타입으로 추론되는 파라미터를 주석에서 제거합니다.
- 함수의 설명을 더 추상적으로 자연어에 가깝게 표현합니다.
- `mapValues(users, 'age')`과 같이 실제 함수가 지원하지 않는 케이스를 설명에서 제거합니다.
- `mapKeys`와 `mapValues`의 유닛 테스트를 명시적으로 분리합니다.
> fix(temen): mapKeys, mapValues 설명 수정

- packages/react/src/hooks/useLocalStorage.ts
타입만 봐서는 `useLocalStorage`가 반환하는 값들의 정체를 알기가 어려워서 소스코드보고 설명을 추가했읍니다.
> chore(react): useLocalStorage 훅 설명 추가

- packages/temen/src/iif/index.ts
- packages/temen/src/index.ts
- packages/temen/src/replaceItem/index.ts
- packages/temen/test/iif.test.js
- packages/temen/test/replaceItem.test.js
배열 내에서 원하는 원소를 Replace할 수 있는 `replaceItem`, `preserveRefReplaceItem` 함수를 추가합니다.
```ts
const foo = [1, 2, 3];
const replacedFoo = replaceItem(foo, 2, 5); // [1, 2, 5]
console.log(foo === replacedFoo); // false, 원본 배열 foo를 건드리지 않고 새로운 배열을 생성함
const bar = [1, 2, 3];
preserveRefReplaceItem(bar, 2, 5); 
console.log(bar); // [1, 2, 5], 원본 배열 bar를 직접 변경함
```
`rxjs`의 `iif`와 유사하게 첫 번째 인자의 참/거짓 결과에 따라 해당하는 값을 반환하는 `iif` 함수를 추가합니다.
```ts
import { iif } from '@quotalab/utils';
const env = iif(typeof window === undefined, 'server', 'client');
const newSignatures = signatures.map(signature => 
iif(signature.id === selectedSignature, signature, null)
)
```
지금 만드는 사이드 프로젝트에서 `replaceItem`이 필요함 ㅜㅜㅜㅜ
> feat(temen): replaceItem, preserveRefReplaceItem, iif 추가

- packages/react/src/hooks/useTabVisibility.ts
- packages/react/src/index.ts
-  page visibility API를 사용하여 사용자가 웹사이트에서 활성 상태인지 비활성 상태인지 확인합니다.
- 사용자가 활성 상태가 아니면 무거운 백그라운드 프로세스를 중지하기 위해 사용 할 수 있습니다.
> Developers have historically used imperfect proxies to detect this. For example, watching for [blur](https://developer.mozilla.org/en-US/docs/Web/API/Window/blur_event) and [focus](https://developer.mozilla.org/en-US/docs/Web/API/Window/focus_event) events on the window helps you know when your page is not the active page, but it does not tell you that your page is actually hidden to the user. The Page Visibility API addresses this. - [MDN](https://developer.mozilla.org/en-US/docs/Web/API/Page_Visibility_API)
> feat(react): add useTabVisibility

- packages/temen/src/entries/index.ts
- packages/temen/test/entries.test.js
`Object.entries`와 동일한 동작이지만 결과 값의 타입을 더 정밀하게 추론하는 `entries` 함수를 추가합니다.
```ts
const foo = { name: 'john', age: 31 };
const entry = entries(foo); // Entry<{ name: string; age: number }>
const element = entry[0]; // ["name", string] | ["age", number] => 키와 값의 쌍을 추론할 수 있다
const originEntry = Object.entries(foo); // [string, string | number][]
const element2 = originEntry[0]; // [string, string | number]
```
🙇
> feat(temen): entries 함수 추가
